### ISSUE TITLE
publish views_googlenews to drupal.org

### ISSUE THREAD

**Issue by braindrifthh** [md-systems/views_googlenews#2]
Hi,

are there any plans to publish this module to drupal.org?

Best regards

**Comment by Berdir** [comment]
Sorry for the delay, that finally happend as I'm in the process of adding it to another project.

https://www.drupal.org/project/views_googlenews

Will do a release once I've completed testing in the new project.

**Comment by braindrifthh** [comment]
Great, Thanks!
